# This is a basic workflow to help you get started with Actions

name: ElectronBuild for Linux

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  BuildForUbuntu:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        name: 'Checkout'

      - name: Install Dependencies
        run: |
          sudo apt install curl
          curl -o ossutil https://gosspublic.alicdn.com/ossutil/1.7.14/ossutil64?spm=a2c4g.11186623.0.0.128b7786ZaZdXf
          sudo chmod 777 ossutil
          ls && pwd
          sudo ln -s ./ossutil /usr/bin/

      - name: Clone and package
        run: | 
          git clone https://tentech:${{secrets.token}}@gitee.com/tentech/fkit.git
          cd ./fkit
          mkdir -p dist
          mkdir -p dist/fkit_windows_386
          mkdir -p dist/fkit_windows_amd64
          mkdir -p dist/fkit_linux_386
          mkdir -p dist/fkit_linux_amd64
          mkdir -p dist/fkit_linux_arm64
          mkdir -p dist/fkit_darwin_amd64
          mkdir -p dist/fkit_darwin_arm64
          ls dist

      - name: Build
        uses: crazy-max/ghaction-xgo@v2
        with:
          xgo_version: latest
          go_version: 1.18
          dest: dist
          prefix: fkit
          targets: windows/386,windows/amd64,linux/386,linux/amd64,linux/arm64,darwin/arm64,darwin/amd64
          v: true
          x: false
          race: false
          ldflags: -s -w
          buildmode: default
          trimpath: true
          working_dir: ./fkit/
      - name: Upload Package
        run: |
          cd ./fkit && ls -la ./dist/ 
          mv ./dist/fkit-windows-386.exe dist/fkit_windows_386/fkit.exe
          mv ./dist/fkit-windows-amd64.exe dist/fkit_windows_amd64/fkit.exe
          mv ./dist/fkit-linux-386 dist/fkit_linux_386/fkit
          mv ./dist/fkit-linux-amd64 dist/fkit_linux_amd64/fkit
          mv ./dist/fkit-linux-arm64 dist/fkit_linux_arm64/fkit
          mv ./dist/fkit-darwin-amd64 dist/fkit_darwin_amd64/fkit
          mv ./dist/fkit-darwin-arm64 dist/fkit_darwin_arm64/fkit
          cd dist/
          zip -r fkit.zip ./fkit_windows_386/
          ossutil -i ${{secrets.accesskey}} -k ${{secrets.accesssecret}} -e oss-cn-hangzhou.aliyuncs.com cp -f ./fkit.zip oss://flowhub-master/publish/fkit_windows_386/fkit.zip
          rm fkit.zip
          
          zip -r fkit.zip ./fkit_windows_amd64/
          ossutil -i ${{secrets.accesskey}} -k ${{secrets.accesssecret}} -e oss-cn-hangzhou.aliyuncs.com cp -f ./fkit.zip oss://flowhub-master/publish/fkit_windows_amd64/fkit.zip
          rm fkit.zip

          zip -r fkit.zip ./fkit_linux_386/
          ossutil -i ${{secrets.accesskey}} -k ${{secrets.accesssecret}} -e oss-cn-hangzhou.aliyuncs.com cp -f ./fkit.zip oss://flowhub-master/publish/fkit_linux_386/fkit.zip
          rm fkit.zip

          zip -r fkit.zip ./fkit_linux_amd64/
          ossutil -i ${{secrets.accesskey}} -k ${{secrets.accesssecret}} -e oss-cn-hangzhou.aliyuncs.com cp -f ./fkit.zip oss://flowhub-master/publish/fkit_linux_amd64/fkit.zip
          rm fkit.zip

          zip -r fkit.zip ./fkit_linux_arm64/
          ossutil -i ${{secrets.accesskey}} -k ${{secrets.accesssecret}} -e oss-cn-hangzhou.aliyuncs.com cp -f ./fkit.zip oss://flowhub-master/publish/fkit_linux_arm64/fkit.zip
          rm fkit.zip

          zip -r fkit.zip ./fkit_darwin_amd64/
          ossutil -i ${{secrets.accesskey}} -k ${{secrets.accesssecret}} -e oss-cn-hangzhou.aliyuncs.com cp -f ./fkit.zip oss://flowhub-master/publish/fkit_darwin_amd64/fkit.zip
          rm fkit.zip

          zip -r fkit.zip ./fkit_darwin_arm64/
          ossutil -i ${{secrets.accesskey}} -k ${{secrets.accesssecret}} -e oss-cn-hangzhou.aliyuncs.com cp -f ./fkit.zip oss://flowhub-master/publish/fkit_darwin_arm64/fkit.zip



